package se.lth.cs.mlir.backend;

import ch.epfl.vlsc.platformutils.Emitter;
import ch.epfl.vlsc.platformutils.PathUtils;
import org.multij.Binding;
import org.multij.BindingKind;
import org.multij.Module;
import se.lth.cs.tycho.ir.entity.PortDecl;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

@Module
/**
 * A class that generates a testbench for the Top verilog module generated by MLIR.
 */
public interface TestbenchGenerator {
    @Binding(BindingKind.INJECTED)
    MlirBackend backend();

    default Emitter emitter() {
        return backend().emitter();
    }

    /**
     * Create the top_tb.sv file and generate the testbench within it.
     * <p>
     * This file contains:
     * 1. A TOP Device under test (DUT)
     * 2. Registers connected to the DUT input signals.
     * 3. Wires connected to the DUT output signals.
     * 4. A clock and reset signal - the clock oscillates and the reset signal is asserted for a few clock cycles at the
     * start of simulation
     * 5. The input bit and valid signals are toggled a few times so the output can be seen.
     * <p>
     * NOTE: The toggling of signals in (5) above is not done very intelligently, so depending on your FIFO design
     * some inputs may be missed. Rather see these generated signals as a starting point - modify them to suit your
     * needs.
     */
    default void generateTestbench() {
        Path mainTarget = PathUtils.getTargetTestbench(backend().context()).resolve("top_tb.sv");
        emitter().open(mainTarget);

        List<String> inputPorts = new ArrayList<>();
        List<String> outputPorts = new ArrayList<>();

        for (PortDecl port : backend().task().getNetwork().getInputPorts()) {
            inputPorts.add(port.getName());
        }
        for (PortDecl port : backend().task().getNetwork().getOutputPorts()) {
            outputPorts.add(port.getName());
        }

        emitter().emit("// A very rudimentary testbench for the generate top MLIR module. The timing on the signals " +
                "is not well though out so the DUT may not always pick up the signal, you may want to modify the " +
                "input signals yourself.");
        emitter().emit("`timescale 1ns / 10ps");
        emitter().emitNewLine();
        emitter().emit("module top_tb;");
        emitter().emitNewLine();

        emitter().emit("// Registers for input signals");
        for (String portName : inputPorts) {
            emitter().emit("reg [31:0] %s_bits = 0;", portName);
            emitter().emit("reg        %s_valid = 0;", portName);
            emitter().emit("reg        %s_close = 0;", portName);
        }
        for (String portName : outputPorts) {
            emitter().emit("reg        %s_ready = 0;", portName);
        }
        emitter().emit("reg        clock = 1, reset = 0;");
        emitter().emitNewLine();

        emitter().emit("// Wires for output signals");
        for (String portName : inputPorts) {
            emitter().emit("wire        %s_ready;", portName);
        }
        for (String portName : outputPorts) {
            emitter().emit("wire        %s_valid;", portName);
            emitter().emit("wire [31:0] %s_bits;", portName);
            emitter().emit("wire        %s_done;", portName);
        }
        emitter().emitNewLine();

        emitter().emit("// Connect testbench to top module");
        emitter().emit("top dut(");
        String inputPortsDutConnect =
                inputPorts.stream().map(x -> x + "_ready, " + x + "_valid, " + x + "_bits, " + x + "_close").collect(Collectors.joining(", "));
        String outputPortsDutConnect =
                outputPorts.stream().map(x -> x + "_ready, " + x + "_valid, " + x + "_bits, " + x + "_done").collect(Collectors.joining(", "));
        String portsList = "clock, reset";
        if (!inputPortsDutConnect.isEmpty()) {
            portsList += ", " + inputPortsDutConnect;
        }
        if (!outputPortsDutConnect.isEmpty()) {
            portsList += ", " + outputPortsDutConnect;
        }

        emitter().emit("\t%s", portsList);
        emitter().emit(");");
        emitter().emitNewLine();


        emitter().emit("// Create clock signal");
        emitter().emit("always #5 clock=~clock;");
        emitter().emitNewLine();

        int nextVal = 10;
        emitter().emit("// Block toggling signals for testing");
        emitter().emit("initial begin");
        emitter().increaseIndentation();
        emitter().emit("reset = 1;");
        emitter().emit("# 60");
        emitter().emit("reset = 0;");
        for (String portName : outputPorts) {
            emitter().emit("%s_ready = 1;", portName);
        }
        emitter().emitNewLine();
        emitter().emit("// Toggle signals a few times to see behaviour over time");
        for (int i = 0; i < 5; i++) {
            emitter().emit("# 50");
            for (String portName : inputPorts) {
                emitter().emit("%s_bits = %d;", portName, nextVal);
                nextVal += 10;
                emitter().emit("%s_valid = 1;", portName);
            }
            emitter().emit("# 10");
            for (String portName : inputPorts) {
                emitter().emit("%s_valid = 0;", portName);
            }
            emitter().emitNewLine();
        }


        emitter().decreaseIndentation();
        emitter().emit("end");
        emitter().emitNewLine();


        emitter().emit("endmodule");
        emitter().close();
    }

}
